version: '3'
services:
  postgres:
    image: postgres:12.1
    ports:
      - 5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_cache:/bundle
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres@postgres
volumes:
  bundle_cache:
