Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'product_index#index'

  get '/webpay_plus/create', to: 'webpay_plus#create'
  get '/webpay_plus/commit', to: 'webpay_plus#commit'
  get '/webpay_plus/status', to: 'webpay_plus#status'
  post '/webpay_plus/refund', to: 'webpay_plus#refund'
  get '/webpay_plus/refund', to: 'webpay_plus#show_refund'

  get '/webpay_plus_deferred/create', to: 'webpay_plus_deferred#create'
  get '/webpay_plus_deferred/commit', to: 'webpay_plus_deferred#commit'
  post '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#capture'
  get '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#show_capture'
  get '/webpay_plus_deferred/status', to: 'webpay_plus_deferred#status'
  post '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#refund'
  get '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#show_refund'
  # post '/webpay_plus_deferred/increase_amount', to: 'webpay_plus_deferred#increase_amount'
  # post '/webpay_plus_deferred/reverse', to: 'webpay_plus_deferred#reverse'
  # post '/webpay_plus_deferred/increase_date', to: 'webpay_plus_deferred#increase_date'
  # post '/webpay_plus_deferred/history', to: 'webpay_plus_deferred#history'

  get '/webpay_plus_mall/create', to: 'webpay_plus_mall#create'
  get '/webpay_plus_mall/commit', to: 'webpay_plus_mall#commit'
  get '/webpay_plus_mall/status', to: 'webpay_plus_mall#status'
  post '/webpay_plus_mall/refund', to: 'webpay_plus_mall#refund'
  get '/webpay_plus_mall/refund', to: 'webpay_plus_mall#show_refund'

  get '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#create'
  post '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#send_create'
  get '/webpay_plus_mall_deferred/commit', to: 'webpay_plus_mall_deferred#commit'
  post 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#capture'
  get 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#show_capture'
  get '/webpay_plus_mall_deferred/status', to: 'webpay_plus_mall_deferred#status'
  post '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#refund'
  get '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#show_refund'
  # post '/webpay_plus_mall_deferred/increase_amount', to: 'webpay_plus_mall_deferred#increase_amount'
  # post '/webpay_plus_mall_deferred/reverse', to: 'webpay_plus_mall_deferred#reverse'
  # post '/webpay_plus_mall_deferred/increase_date', to: 'webpay_plus_mall_deferred#increase_date'
  # post '/webpay_plus_mall_deferred/history', to: 'webpay_plus_mall_deferred#history'

  get '/oneclick_mall/start', to: 'oneclick_mall#start'
  get '/oneclick_mall/finish', to: 'oneclick_mall#finish'
  delete '/oneclick_mall/delete', to: 'oneclick_mall#delete'
  get '/oneclick_mall/authorize', to: 'oneclick_mall#authorize'
  get '/oneclick_mall/status', to: 'oneclick_mall#status'
  post '/oneclick_mall/refund', to: 'oneclick_mall#refund'
  get '/oneclick_mall/refund', to: 'oneclick_mall#show_refund'

  get '/oneclick_mall_deferred/start', to: 'oneclick_mall_deferred#start'
  get '/oneclick_mall_deferred/finish', to: 'oneclick_mall_deferred#finish'
  delete '/oneclick_mall_deferred/delete', to: 'oneclick_mall_deferred#delete'
  get '/oneclick_mall_deferred/authorize', to: 'oneclick_mall_deferred#authorize'
  get '/oneclick_mall_deferred/status', to: 'oneclick_mall_deferred#status'
  post '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#refund'
  get '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#show_refund'
  post '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#capture'
  get '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#show_capture'
  # post '/oneclick_mall_deferred/increase_amount', to: 'oneclick_mall_deferred#increase_amount'
  # post '/oneclick_mall_deferred/reverse', to: 'oneclick_mall_deferred#reverse'
  # post '/oneclick_mall_deferred/increase_date', to: 'oneclick_mall_deferred#increase_date'
  # post '/oneclick_mall_deferred/history', to: 'oneclick_mall_deferred#history'

  get '/transaccion_completa/form', to: 'transaccion_completa#form'
  post '/transaccion_completa/create', to: 'transaccion_completa#create'
  get '/transaccion_completa/create', to: 'transaccion_completa#show_create'
  post '/transaccion_completa/installments', to: 'transaccion_completa#installments'
  get '/transaccion_completa/installments', to: 'transaccion_completa#show_installments'
  post '/transaccion_completa/commit', to: 'transaccion_completa#commit'
  get '/transaccion_completa/commit', to: 'transaccion_completa#show_commit'
  get  '/transaccion_completa/status', to: 'transaccion_completa#status'
  post '/transaccion_completa/refund', to: 'transaccion_completa#refund'
  get '/transaccion_completa/refund', to: 'transaccion_completa#show_refund'

  get '/transaccion_completa_deferred/form', to: 'transaccion_completa_deferred#form'
  post '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#create'
  get '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#show_create'
  post '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#installments'
  get '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#show_installments'
  post '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#commit'
  get '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#show_commit'
  post '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#capture'
  get '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#show_capture'
  get  '/transaccion_completa_deferred/status', to: 'transaccion_completa_deferred#status'
  post '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#refund'
  get '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#show_refund'
  # post '/transaccion_completa_deferred/increase_amount', to: 'transaccion_completa_deferred#increase_amount'
  # post '/transaccion_completa_deferred/reverse', to: 'transaccion_completa_deferred#reverse'
  # post '/transaccion_completa_deferred/increase_date', to: 'transaccion_completa_deferred#increase_date'
  # post '/transaccion_completa_deferred/history', to: 'transaccion_completa_deferred#history'

  get '/transaccion_completa_mall/form', to: 'transaccion_completa_mall#form'
  post '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#create'
  get '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#show_create'
  post '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#installments'
  get '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#show_installments'
  post '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#commit'
  get '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#show_commit'
  get  '/transaccion_completa_mall/status', to: 'transaccion_completa_mall#status'
  post '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#refund'
  get '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#show_refund'

  get '/transaccion_completa_mall_deferred/form', to: 'transaccion_completa_mall_deferred#form'
  post '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#create'
  get '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#show_create'
  post '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#installments'
  get '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#show_installments'
  post '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#commit'
  get '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#show_commit'
  post '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#capture'
  get '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#show_capture'
  get  '/transaccion_completa_mall_deferred/status', to: 'transaccion_completa_mall_deferred#status'
  post '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#refund'
  get '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#show_refund'
  # post '/transaccion_completa_mall_deferred/increase_amount', to: 'transaccion_completa_mall_deferred#increase_amount'
  # post '/transaccion_completa_mall_deferred/reverse', to: 'transaccion_completa_mall_deferred#reverse'
  # post '/transaccion_completa_mall_deferred/increase_date', to: 'transaccion_completa_mall_deferred#increase_date'
  # post '/transaccion_completa_mall_deferred/history', to: 'transaccion_completa_mall_deferred#history'

  get '/patpass_comercio/start', to: 'patpass_comercio#start'
  post '/patpass_comercio/commit', to: 'patpass_comercio#commit'
  post '/patpass_comercio/commit', to: 'patpass_comercio#show_commit'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#voucher_return'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#show_voucher_return'

end
